services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    dockerfilePath: ./dockerfile
    dockerContext: .

    envVars:
      - key: DB_HOST
        fromDatabase:
          name: expense_tracker
          property: host

      - key: DB_PORT
        fromDatabase:
          name: expense_tracker
          property: port

      - key: DB_NAME
        fromDatabase:
          name: expense_tracker
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: expense_tracker
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: expense_tracker
          property: password

databases:
  - name: expense_tracker
    plan: free